ci:

diff --git a/.github/workflows/flutter_ci.yml b/.github/workflows/flutter_ci.yml
--- a/.github/workflows/flutter_ci.yml
+++ b/.github/workflows/flutter_ci.yml
@@ -38,11 +38,19 @@ jobs:
         apk_path=$(find ./build/app/outputs/apk/release -name '*.apk' | head -n 1)
         echo "APK_PATH=$apk_path" >> $GITHUB_ENV
         echo "::set-output name=apk_path::$apk_path"
+        echo "Found APK at $apk_path"
 
     - name: Send APK
       if: github.ref == 'refs/heads/main'
       run: |
-        curl --request POST \
-             --url ${{ secrets.API_ENDPOINT }} \
-             --header 'Content-Type: multipart/form-data' \
-             --form "file=@${{ env.APK_PATH }}"
+        echo "Sending APK..."
+        response=$(curl --write-out "%{http_code}" --silent --output /dev/null --request POST \
+                 --url ${{ secrets.API_ENDPOINT }} \
+                 --header 'Content-Type: multipart/form-data' \
+                 --form "file=@${{ env.APK_PATH }}")
+        echo "Response code: $response"
+        if [ "$response" -ne 200 ]; then
+          echo "Error: Failed to send APK. Response code: $response"
+          exit 1
+        else
+          echo "APK sent successfully."
